baseURL = 'https://htakeuchi0.github.io/'
languageCode = 'ja-jp'
title = 'htakeuchi0 のノート'
theme = 'hugo-book'
enableGitInfo = true

[params]
  BookTheme = 'auto'
  BookRepo = 'https://github.com/htakeuchi0/htakeuchi0.github.io'

[menu]
  [[menu.after]]
    identifier = "disclaimer"
    name = "免責事項"
    title = "免責事項"
    url = "/#disclaimer"
    weight = 1

  [[menu.after]]
    identifier = "privacy_policy"
    name = "プライバシーポリシー"
    title = "プライバシーポリシー"
    url = "/#privacy_policy"
    weight = 2
